[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# Version is now managed through a VERSION file in the repository root
# This ensures all users have the same version information